In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

## aam Jindagi

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    str
 2   fever      90 non-null     float64
 3   cough      100 non-null    str
 4   city       100 non-null    str
 5   has_covid  100 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 4.8 KB

In [20]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [21]:
df['fever'].value_counts()

fever
101.0    17
98.0     17
104.0    14
100.0    13
99.0     10
102.0    10
103.0     9
Name: count, dtype: int64

In [10]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [11]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [12]:
# categorical col
    # gender,city -> nominal categorical
    # cough -> ordinal categorical
# numerical col
    # fever -> missing values - SimpleImputer

In [65]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:5], df.iloc[:,-1], test_size=0.2, random_state=42)

X_train.head()

    age  gender  fever cough     city
55   81  Female  101.0  Mild   Mumbai
88    5  Female  100.0  Mild  Kolkata
26   19  Female  100.0  Mild  Kolkata
42   27    Male  100.0  Mild    Delhi
69   73  Female  103.0  Mild    Delhi

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer

In [46]:
imp = SimpleImputer()
X_train_fever = imp.fit_transform(X_train[['fever']])
X_test_fever = imp.transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [57]:
ohe = OneHotEncoder(sparse_output=False, drop='first',dtype='int32')
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city = ohe.transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [67]:
ord_enc = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = ord_enc.fit_transform(X_train[['cough']])
X_test_cough = ord_enc.transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [71]:
X_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

In [76]:
transformer = ColumnTransformer(transformers = [
    ('tfn1', SimpleImputer(), ['fever']),
    ('tfn2', OneHotEncoder(sparse_output=False, drop='first',dtype='int32'), ['gender','city']),
    ('tfn3', OrdinalEncoder(categories=[['Mild','Strong']]), ['cough'])
    
], remainder='passthrough')

In [82]:
transformer.fit_transform(X_train).shape
transformer.transform(X_test).shape

(20, 7)